# 
# Sunbeam configuration file
#
# Defining samples:
#   Run 'sunbeam list_samples <data_dir>' to create a list of samples and
#   associated fastq.gz files. Samples must be in gzipped fastq format.
#
# Paths:
#   Paths are resolved through the following rules:
#     1. If the path is absolute, the path is parsed as-is
#     2. If the path is not absolute, the path at 'root' is appended to it
#     3. If the path is not 'output_fp', the path is checked to ensure it exists
#
# Suffixes:
#   Each subsection contains a 'suffix' key that defines the folder under
#   'output_fp' where the results of that section are put.
#

# General options
all:
  root: /mnt/d/Penn/sunbeam/projects/WGS-test
  output_fp: sunbeam_output
  samplelist_fp: samples.csv
  paired_end: true
  download_reads: false
  version: 3.0.1+dev7.g354d604
qc:
  suffix: qc
  seq_id_ending: ''
  threads: 4
  java_heapsize: 512M
  leading: 3
  trailing: 3
  slidingwindow: [4, 15]
  minlen: 36
  adapter_template: $CONDA_PREFIX/share/trimmomatic/adapters/NexteraPE-PE.fa
  fwd_adapters: [GTTTCCCAGTCACGATC, GTTTCCCAGTCACGATCNNNNNNNNNGTTTCCCAGTCACGATC]
  rev_adapters: [GTTTCCCAGTCACGATC, GTTTCCCAGTCACGATCNNNNNNNNNGTTTCCCAGTCACGATC]
  kz_threshold: 0.55
  pct_id: 0.5
  frac: 0.6
  host_fp: ''
classify:
  suffix: classify
  threads: 4
  kraken_db_fp: ''
assembly:
  suffix: assembly
  min_length: 300
  threads: 4
annotation:
  suffix: annotation
  min_contig_len: 500
  circular_kmin: 10
  circular_kmax: 1000
  circular_min_len: 3500
blast:
  threads: 4
blastdbs:
  root_fp: ''
mapping:
  suffix: mapping
  genomes_fp: ''
  samtools_opts: ''
  threads: 4
download:
  suffix: download
  threads: 4
# Per-rule computational resource usage data
benchmarks:
  suffix: benchmarks
# Logs
logs:
  suffix: logs
sbx_coassembly:
  threads: 4
  group_file: ''
sbx_demic:
  threads: 4 #--thread_num
  keepall: FALSE #--output_all
  extras: "" # Other parameters passed to DEMIC.pl
sbx_WGS:
  threads: 4
  metagenome: FALSE
  checkm_yml: # Leave blank if not wanted
  window_size: 5000
  sampling: 5000
sbx_gene_clusters:
  threads: 8
  genes_fp: sbx_gene_family/database
  evalue: 1e-5
  alnLen: 30
  mismatch: 3
sbx_kraken:
  kraken_db_fp: ''
sbx_mapping:
  genomes_fp: ''
  samtools_opts: ''