name: Push to DockerHub

on:
  workflow_call:

  workflow_dispatch:

jobs:
    push-dockerhub:
        name: Push to Dockerhub
        runs-on: ubuntu-latest
    
        steps:
          - uses: actions/checkout@v4
          
          - name: Log in to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}
          
          - name: Extract metadata (tags, labels) for Docker
            id: meta
            uses: docker/metadata-action@v5
            with:
              images: ctbushman/sunbeam

          - name: Debug
            run: |
              echo "Tags: ${{ steps.meta.outputs.tags }}"
              echo "Labels: ${{ steps.meta.outputs.labels }}"
          
          - name: Build and push Docker image
            uses: docker/build-push-action@v5
            with:
              context: .
              file: ./Dockerfile
              push: true
              tags: ${{ steps.meta.outputs.tags }}
              labels: ${{ steps.meta.outputs.labels }}