name: Push to DockerHub

on:
  workflow_call:

  workflow_dispatch:

jobs:
    push-dockerhub:
        name: Push to Dockerhub
        runs-on: ubuntu-latest
    
        steps:
          - uses: actions/checkout@v4

          - id: get_version
            uses: battila7/get-version-action@v2
          
          - name: Log in to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}
          
          - name: Extract metadata (tags, labels) for Docker
            id: meta
            uses: docker/metadata-action@v5
            with:
              images: sunbeamlabs/sunbeam

          - name: Build test
            uses: docker/build-push-action@v5
            with:
              context: .
              file: ./Dockerfile
              load: true
              tags: sunbeamlabs/sunbeam:test

          - name: Test
            run: |
              docker run --rm sunbeamlabs/sunbeam:test pytest tests/
            
          - name: Build slim test
            uses: docker/build-push-action@v5
            with:
              context: .
              file: ./slim.Dockerfile
              load: true
              tags: sunbeamlabs/sunbeam:test-slim

          - name: Test slim
            run: |
              docker run --rm sunbeamlabs/sunbeam:test-slim pytest tests/
          
          - name: Build and push Docker image
            uses: docker/build-push-action@v5
            with:
              context: .
              file: ./Dockerfile
              push: true
              tags: sunbeamlabs/sunbeam:latest, sunbeamlabs/sunbeam:${{ steps.get_version.outputs.version-without-v }}
              labels: ${{ steps.meta.outputs.labels }}

          - name: Build and push slim Docker image
            uses: docker/build-push-action@v5
            with:
              context: .
              file: ./slim.Dockerfile
              push: true
              tags: sunbeamlabs/sunbeam:${{ steps.get_version.outputs.version-without-v }}-slim
              labels: ${{ steps.meta.outputs.labels }}

    push-cutadapt-dockerhub:
      name: Push cutadapt env to Dockerhub
      runs-on: ubuntu-latest
  
      steps:
        - uses: actions/checkout@v4
        
        - name: Log in to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        
        - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@v5
          with:
            images: sunbeamlabs/cutadapt
        
        - name: Build and push Docker image
          uses: docker/build-push-action@v5
          with:
            context: .
            file: workflow/envs/cutadapt.Dockerfile
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}

    push-komplexity-dockerhub:
      name: Push komplexity env to Dockerhub
      runs-on: ubuntu-latest
  
      steps:
        - uses: actions/checkout@v4
        
        - name: Log in to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        
        - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@v5
          with:
            images: sunbeamlabs/komplexity
        
        - name: Build and push Docker image
          uses: docker/build-push-action@v5
          with:
            context: .
            file: workflow/envs/komplexity.Dockerfile
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}

    push-qc-dockerhub:
      name: Push qc env to Dockerhub
      runs-on: ubuntu-latest
  
      steps:
        - uses: actions/checkout@v4
        
        - name: Log in to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        
        - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@v5
          with:
            images: sunbeamlabs/qc
        
        - name: Build and push Docker image
          uses: docker/build-push-action@v5
          with:
            context: .
            file: workflow/envs/qc.Dockerfile
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}

    push-reports-dockerhub:
      name: Push reports env to Dockerhub
      runs-on: ubuntu-latest
  
      steps:
        - uses: actions/checkout@v4
        
        - name: Log in to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        
        - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@v5
          with:
            images: sunbeamlabs/reports
        
        - name: Build and push Docker image
          uses: docker/build-push-action@v5
          with:
            context: .
            file: workflow/envs/reports.Dockerfile
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}