name: Push to DockerHub

on:
  workflow_call:
    inputs:
      version:
        description: "Sunbeam version"
        required: true
        type: string
    outputs:
      sunbeam_package_versions:
        description: "Versions in main Sunbeam image"
        value: ${{ jobs.push-dockerhub.outputs.package_versions }}
      sunbeam_package_versions_slim:
        description: "Versions in slim Sunbeam image"
        value: ${{ jobs.push-dockerhub.outputs.package_versions_slim }}
      cutadapt_package_versions:
        description: "Versions in cutadapt image"
        value: ${{ jobs.push-cutadapt-dockerhub.outputs.package_versions }}
      komplexity_package_versions:
        description: "Versions in komplexity image"
        value: ${{ jobs.push-komplexity-dockerhub.outputs.package_versions }}
      qc_package_versions:
        description: "Versions in qc image"
        value: ${{ jobs.push-qc-dockerhub.outputs.package_versions }}
      reports_package_versions:
        description: "Versions in reports image"
        value: ${{ jobs.push-reports-dockerhub.outputs.package_versions }}

  workflow_dispatch:

jobs:
    push-dockerhub:
        name: Push to Dockerhub
        runs-on: ubuntu-latest

        outputs:
          package_versions: ${{ steps.report.outputs.package_versions }}
          package_versions_slim: ${{ steps.report.outputs.package_versions_slim }}
    
        steps:
          - uses: actions/checkout@v4
          
          - name: Log in to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
          
          - name: Extract metadata (tags, labels) for Docker
            id: meta
            uses: docker/metadata-action@v5
            with:
              images: sunbeamlabs/sunbeam

          - name: Build test
            uses: docker/build-push-action@v5
            with:
              context: .
              file: ./Dockerfile
              load: true
              tags: sunbeamlabs/sunbeam:test

          - name: Test
            run: |
              docker run --rm sunbeamlabs/sunbeam:test pytest tests/
            
          - name: Build slim test
            uses: docker/build-push-action@v5
            with:
              context: .
              file: ./slim.Dockerfile
              load: true
              tags: sunbeamlabs/sunbeam:test-slim

          - name: Test slim
            run: |
              docker run --rm sunbeamlabs/sunbeam:test-slim pytest tests/
          
          - name: Build and push Docker image
            uses: docker/build-push-action@v5
            with:
              context: .
              file: ./Dockerfile
              push: true
              tags: sunbeamlabs/sunbeam:latest, sunbeamlabs/sunbeam:${{ inputs.version }}
              labels: ${{ steps.meta.outputs.labels }}
              build-args: "SUNBEAM_VER=${{ inputs.version }}"

          - name: Build and push slim Docker image
            uses: docker/build-push-action@v5
            with:
              context: .
              file: ./slim.Dockerfile
              push: true
              tags: sunbeamlabs/sunbeam:${{ inputs.version }}-slim
              labels: ${{ steps.meta.outputs.labels }}
              build-args: "SUNBEAM_VER=${{ inputs.version }}"

          - name: Generate image report
            id: report
            run: |
              echo "package_versions=$(docker run --rm sunbeamlabs/sunbeam:${{ inputs.version }} cat installed_packages.txt)" >> "$GITHUB_OUTPUT"
              echo "package_versions_slim=$(docker run --rm sunbeamlabs/sunbeam:${{ inputs.version }}-slim cat installed_packages.txt)" >> "$GITHUB_OUTPUT"

    push-cutadapt-dockerhub:
      name: Push cutadapt env to Dockerhub
      runs-on: ubuntu-latest

      outputs:
        package_versions: ${{ steps.report.outputs.package_versions }}
  
      steps:
        - uses: actions/checkout@v4
        
        - name: Log in to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        
        - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@v5
          with:
            images: sunbeamlabs/cutadapt
        
        - name: Build and push Docker image
          uses: docker/build-push-action@v5
          with:
            context: .
            file: workflow/envs/cutadapt.Dockerfile
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}

        - name: Generate image report
          id: report
          run: |
            echo "package_versions=$(docker run --rm sunbeamlabs/cutadapt:${{ inputs.version }} cat installed_packages.txt)" >> "$GITHUB_OUTPUT"

    push-komplexity-dockerhub:
      name: Push komplexity env to Dockerhub
      runs-on: ubuntu-latest

      outputs:
        package_versions: ${{ steps.report.outputs.package_versions }}
  
      steps:
        - uses: actions/checkout@v4
        
        - name: Log in to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        
        - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@v5
          with:
            images: sunbeamlabs/komplexity
        
        - name: Build and push Docker image
          uses: docker/build-push-action@v5
          with:
            context: .
            file: workflow/envs/komplexity.Dockerfile
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}

        - name: Generate image report
          id: report
          run: |
            echo "package_versions=$(docker run --rm sunbeamlabs/komplexity:${{ inputs.version }} cat installed_packages.txt)" >> "$GITHUB_OUTPUT"

    push-qc-dockerhub:
      name: Push qc env to Dockerhub
      runs-on: ubuntu-latest

      outputs:
        package_versions: ${{ steps.report.outputs.package_versions }}
  
      steps:
        - uses: actions/checkout@v4
        
        - name: Log in to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        
        - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@v5
          with:
            images: sunbeamlabs/qc
        
        - name: Build and push Docker image
          uses: docker/build-push-action@v5
          with:
            context: .
            file: workflow/envs/qc.Dockerfile
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}

        - name: Generate image report
          id: report
          run: |
            echo "package_versions=$(docker run --rm sunbeamlabs/qc:${{ inputs.version }} cat installed_packages.txt)" >> "$GITHUB_OUTPUT"

    push-reports-dockerhub:
      name: Push reports env to Dockerhub
      runs-on: ubuntu-latest

      outputs:
        package_versions: ${{ steps.report.outputs.package_versions }}
  
      steps:
        - uses: actions/checkout@v4
        
        - name: Log in to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        
        - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@v5
          with:
            images: sunbeamlabs/reports
        
        - name: Build and push Docker image
          uses: docker/build-push-action@v5
          with:
            context: .
            file: workflow/envs/reports.Dockerfile
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}

        - name: Generate image report
          id: report
          run: |
            echo "package_versions=$(docker run --rm sunbeamlabs/reports:${{ inputs.version }} cat installed_packages.txt)" >> "$GITHUB_OUTPUT"