name: PR

on:
    pull_request:
      branches:
        - main
    push:
      branches:
        - main

jobs:
    run-tests:
        uses: sunbeam-labs/sunbeam/.github/workflows/tests.yml@${{ github.head_ref || github.ref_name }}
        secrets: inherit

    