name: Release

on:
    release:
      types: [published]

    workflow_dispatch:

jobs:
    run-tests:
        uses: ./.github/workflows/tests.yml
        secrets: inherit
    
    check-version:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4
          - uses: s-weigand/setup-conda@v1.2.1
          - name: Install Sunbeam
            shell: bash
            run: |
                cd $GITHUB_WORKSPACE
                GIT_VERSION=$(bash install.sh -w)
                echo "GIT_VERSION=$GIT_VERSION" >> $GITHUB_ENV

          - name: Download and Extract
            shell: bash
            run: |
                wget https://github.com/sunbeam-labs/sunbeam/releases/latest/download/sunbeam.tar.gz
                mkdir tar_sunbeam
                tar -zxf sunbeam.tar.gz -C tar_sunbeam
                cd tar_sunbeam
                TAR_VERSION=$(bash install.sh -w)
                echo "TAR_VERSION=$TAR_VERSION" >> $GITHUB_ENV

          - id: get_version
            uses: battila7/get-version-action@v2

          - name: Check version
            run: |
                RELEASE_VERSION=${{ steps.get_version.outputs.version-without-v }}
                echo "Release version: ${RELEASE_VERSION}"
                echo "GitHub version: ${{ env.GIT_VERSION }}"
                echo "Tarball version: ${{ env.TAR_VERSION }}"

                if [[ $RELEASE_VERSION == ${{ env.GIT_VERSION }} ]] && [[ ${{ env.GIT_VERSION }} == ${{ env.TAR_VERSION }} ]]; then
                    echo "Versions match, continuing..."
                else
                    echo "Versions don't match, exiting..."
                    exit 1
                fi
    
    test-tarball:
        name: Test Tarball
        runs-on: ubuntu-latest
        needs:
          - run-tests
          - check-version
    
        steps:
          - name: setup-conda
            uses: s-weigand/setup-conda@v1.2.1 
    
          - name: Download and Extract
            shell: bash
            run: |
              wget https://github.com/sunbeam-labs/sunbeam/releases/latest/download/sunbeam.tar.gz
              mkdir sunbeam
              tar -zxf sunbeam.tar.gz -C sunbeam
              cd sunbeam && ./install.sh -e sunbeam
          
          - name: Run Tests
            shell: bash
            run: |
              source activate sunbeam
              cd sunbeam
              pytest -vvl tests/

    push-dockerhub:
        uses: ./.github/workflows/dockerhub.yml
        secrets: inherit
        needs:
          - run-tests
          - check-version

    generate-docker-reports-sunbeam:
        runs-on: ubuntu-latest
        container: sunbeamlabs/sunbeam:latest
        needs: [push-dockerhub]

        outputs:
          snakemake_version: ${{ steps.sunbeam.outputs.snakemake_version }}
          python_version: ${{ steps.sunbeam.outputs.python_version }}

        steps:
          - name: Generate sunbeam image report
            id: sunbeam
            run: |
              echo "snakemake_version=$(snakemake --version)" >> "$GITHUB_OUTPUT"
              echo "python_version=$(python --version)" >> "$GITHUB_OUTPUT"

    generate-docker-reports-cutadapt:
      runs-on: ubuntu-latest
      container: sunbeamlabs/cutadapt:latest
      needs: [push-dockerhub]

      outputs:
        cutadapt_version: ${{ steps.cutadapt.outputs.cutadapt_version }}

      steps:
        - name: Generate cutadapt image report
          id: cutadapt
          run: |
            echo "cutadapt_version=$(cutadapt --version)" >> "$GITHUB_OUTPUT"

    udpate-release-notes:
        name: Update release notes
        runs-on: ubuntu-latest
        needs:
          - generate-docker-reports-sunbeam
          - generate-docker-reports-cutadapt
        
        steps:
          - name: Add Image Reports to Release
            uses: irongut/EditRelease@v1.2.0
            with:
              token: ${{ secrets.GITHUB_TOKEN }}
              id: ${{ github.event.release.id }}
              body: "### sunbeamlabs/sunbeam:latest\nSnakemake: ${{ needs.generate-docker-reports-sunbeam.outputs.snakemake_version }}\nPython: ${{ needs.generate-docker-reports-sunbeam.outputs.python_version }}\n### sunbeamlabs/cutadapt:latest\nCutadapt: ${{ needs.generate-docker-reports-cutadapt.outputs.cutadapt_version }}"
              replacebody: false
        
    run-integration-tests:
        uses: ./.github/workflows/integration-tests.yml
        secrets: inherit
        needs:
            - push-dockerhub
            - test-tarball
