name: Tests

on:
  workflow_call:

  workflow_dispatch:

  schedule:
    - cron: '0 0 * * *'

env:
  CACHE_NUMBER: 0  # increase to reset cache manually

jobs:
  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
            miniforge-variant: Mambaforge
            miniforge-version: latest
            use-mamba: true
    
      - name: Install Sunbeam
        shell: bash
        run: |
            cd $GITHUB_WORKSPACE
            bash install.sh -e sunbeam -v
    
      - name: Run tests
        run: |
          source activate sunbeam
          pytest ./tests/unit/

  e2e_tests:
    name: E2E Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
            miniforge-variant: Mambaforge
            miniforge-version: latest
            use-mamba: true
    
      - name: Install Sunbeam
        shell: bash
        run: |
            cd $GITHUB_WORKSPACE
            bash install.sh -e sunbeam -v
    
      - name: Run tests
        run: |
            source activate sunbeam
            pytest ./tests/e2e/

  lint:
    name: Lint Codebase
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Super-Linter
        uses: github/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          VALIDATE_SNAKEMAKE_SNAKEFMT: true
          VALIDATE_PYTHON_BLACK: true

          FILTER_REGEX_INCLUDE: scripts/.*|rules/.*|sunbeamlib/.*|tests/.*|Snakefile
    
  test-slurm:
    runs-on: ubuntu-latest
    services:
        mysql:
          image: mysql:8.0
          env:
            MYSQL_ROOT_PASSWORD: root
          ports:
            - "8888:3306"
          options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
        - uses: actions/checkout@v4
        - uses: s-weigand/setup-conda@v1.2.1
        - uses: koesterlab/setup-slurm-action@v1

        - name: Install Sunbeam
          shell: bash
          run: |
            cd $GITHUB_WORKSPACE
            bash install.sh -e sunbeam -v
        
        - name: Run Sunbeam
          shell: bash
          run: |
            cd $GITHUB_WORKSPACE
            source activate sunbeam
            mkdir projects/

            pip install snakemake-executor-plugin-slurm

            sunbeam init --data_fp tests/data/reads/ --profile slurm projects/test/

            sunbeam run --default-resources slurm_account=runner --profile projects/test/ test

  test-apptainer:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: s-weigand/setup-conda@v1.2.1
        - uses: eWaterCycle/setup-apptainer@v2
          with:
            apptainer-version: 1.1.2

        - name: Install Sunbeam
          shell: bash
          run: |
            cd $GITHUB_WORKSPACE
            bash install.sh -e sunbeam -v

        - name: Run Sunbeam
          shell: bash
          run: |
            cd $GITHUB_WORKSPACE
            source activate sunbeam
            mkdir projects/

            sunbeam init --data_fp tests/data/reads/ --profile apptainer projects/test/

            sunbeam run --profile projects/test/