name: Tests

on:
  workflow_call:

  workflow_dispatch:

  schedule:
    - cron: '0 0 * * *'

env:
  CACHE_NUMBER: 0  # increase to reset cache manually

jobs:
  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: s-weigand/setup-conda@v1.2.1
    
      - name: Install Sunbeam
        shell: bash
        run: |
            cd $GITHUB_WORKSPACE
            bash install.sh -e sunbeam -v
    
      - name: Run tests
        run: |
          source activate sunbeam
          pytest ./tests/unit/

  lint:
    name: Lint Codebase
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
            python-version: 3.12
      - name: Install Dependencies
        run: pip install black snakefmt

      - name: Lint Code Base
        run: |
            black --check workflow/scripts/ src/sunbeamlib/ tests/
            snakefmt --check workflow/rules/ workflow/Snakefile

  e2e_tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    needs:
        - unit_tests
        - lint

    steps:
      - uses: actions/checkout@v4

      - uses: s-weigand/setup-conda@v1.2.1
    
      - name: Install Sunbeam
        shell: bash
        run: |
            cd $GITHUB_WORKSPACE
            bash install.sh -e sunbeam -v
    
      - name: Run tests
        run: |
            source activate sunbeam
            pytest ./tests/e2e/
    
  test-slurm:
    name: Slurm Test
    runs-on: ubuntu-latest
    services:
        mysql:
          image: mysql:8.0
          env:
            MYSQL_ROOT_PASSWORD: root
          ports:
            - "8888:3306"
          options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    needs:
        - unit_tests
        - lint

    steps:
        - uses: actions/checkout@v4
        - uses: s-weigand/setup-conda@v1.2.1
        - uses: koesterlab/setup-slurm-action@v1

        - name: Install Sunbeam
          shell: bash
          run: |
            cd $GITHUB_WORKSPACE
            bash install.sh -e sunbeam -v
        
        - name: Run Sunbeam
          shell: bash
          run: |
            cd $GITHUB_WORKSPACE
            source activate sunbeam
            mkdir projects/

            pip install snakemake-executor-plugin-slurm

            sunbeam init --data_fp tests/data/reads/ --profile slurm projects/test/

            sunbeam run --default-resources slurm_account=runner --profile projects/test/ test

  test-apptainer:
    name: Apptainer Test
    runs-on: ubuntu-latest
    needs:
        - unit_tests
        - lint

    steps:
        - uses: actions/checkout@v4
        - uses: s-weigand/setup-conda@v1.2.1
        - uses: eWaterCycle/setup-apptainer@v2
          with:
            apptainer-version: 1.1.2

        - name: Install Sunbeam
          shell: bash
          run: |
            cd $GITHUB_WORKSPACE
            bash install.sh -e sunbeam -v

        - name: Run Sunbeam
          shell: bash
          run: |
            cd $GITHUB_WORKSPACE
            source activate sunbeam
            mkdir projects/

            sunbeam init --data_fp tests/data/reads/ --profile apptainer projects/test/

            sunbeam run --profile projects/test/