name: Test Slurm Integration

on:
  pull_request:
    branches: [main]

jobs:
    testing:
      runs-on: ubuntu-latest
      # For the action to work, you have to supply a mysql
      # service as defined below.
      services:
        mysql:
          image: mysql:8.0
          env:
            MYSQL_ROOT_PASSWORD: root
          ports:
            - "8888:3306"
          options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      steps:
        - uses: actions/checkout@v3
  
        - uses: koesterlab/setup-slurm-action@v1

        - uses: s-weigand/setup-conda@v1.1.0

        - name: Install Sunbeam
          shell: bash
          run: |
            git clone --depth 1 --branch ${{ github.head_ref }} https://github.com/sunbeam-labs/sunbeam sunbeam
            cd sunbeam
            bash install.sh -e sunbeam -v
        
        - name: Run Sunbeam
          shell: bash
          run: |
                cd sunbeam
                source activate sunbeam

                mkdir projects/
                sunbeam init --data_fp tests/data/reads/ --profile slurm projects/test/

                sunbeam run --profile projects/test/