name: Tests

on:
  workflow_call:

  workflow_dispatch:

  schedule:
    - cron: '0 0 * * *'

env:
  CACHE_NUMBER: 0  # increase to reset cache manually

jobs:
  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
            miniforge-variant: Mambaforge
            miniforge-version: latest
            activate-environment: sunbeam
            use-mamba: true

      - name: Set cache date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
    
      - uses: actions/cache@v2
        with:
          path: /usr/share/miniconda3/envs/sunbeam
          key: conda-${{ hashFiles('environment.yml') }}-${{ env.DATE }}-${{ env.CACHE_NUMBER }}
        id: cache
    
      - name: Update environment
        run: mamba env update -n sunbeam -f environment.yml
        if: steps.cache.outputs.cache-hit != 'true'
    
      - name: Run tests
        run: |
          source activate sunbeam
          pytest ./tests/unit/